export const CREATESECTION = "CREATESECTION";
export const DELETESECTION = "DELETESECTION";
export const CREATETEXTCHANNEL = "CREATETEXTCHANNEL";
export const CREATEVOICECHANNEL = "CREATEVOICECHANNEL";
export const POSTMESSAGE = "POSTMESSAGE";
export const SETCURRENTCHANNEL = "SETCURRENTCHANNEL";
export const SETCURRENTSECTION = "SETCURRENTSECTION";